title: "Baoshuo DN42 Network"
url: "https://dn42.baoshuo.ren"

exclude:
  - node_modules
  - script
logo: https://cdn.jsdelivr.net/npm/bsi@0.0.3/favicon/128x128.png
twitter:
  username: renbaoshuo
  card: summary

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: true

defaults:
  - scope:
      path: ""
    values:
      image: https://cdn.jsdelivr.net/npm/bsi@0.0.3/favicon/128x128.png
